// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7-H-Dm3EJdcaakEQx_ehWqXJAp2jvgq4',
    appId: '1:809642431817:web:42827edadb057405e53698',
    messagingSenderId: '809642431817',
    projectId: 'pawfinder-ac326',
    authDomain: 'pawfinder-ac326.firebaseapp.com',
    databaseURL: 'https://pawfinder-ac326-default-rtdb.firebaseio.com',
    storageBucket: 'pawfinder-ac326.firebasestorage.app',
    measurementId: 'G-NVEMXQCJ09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHyksB64L9CH6h5YhcDuFMvGb4K9FdDIQ',
    appId: '1:809642431817:android:364555ca54173b2de53698',
    messagingSenderId: '809642431817',
    projectId: 'pawfinder-ac326',
    databaseURL: 'https://pawfinder-ac326-default-rtdb.firebaseio.com',
    storageBucket: 'pawfinder-ac326.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU6X2PYDtvWMJZY9BhgOzAUpBCKlGVfvc',
    appId: '1:809642431817:ios:88f043f21f1346d2e53698',
    messagingSenderId: '809642431817',
    projectId: 'pawfinder-ac326',
    databaseURL: 'https://pawfinder-ac326-default-rtdb.firebaseio.com',
    storageBucket: 'pawfinder-ac326.firebasestorage.app',
    iosBundleId: 'com.example.pawfinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU6X2PYDtvWMJZY9BhgOzAUpBCKlGVfvc',
    appId: '1:809642431817:ios:88f043f21f1346d2e53698',
    messagingSenderId: '809642431817',
    projectId: 'pawfinder-ac326',
    databaseURL: 'https://pawfinder-ac326-default-rtdb.firebaseio.com',
    storageBucket: 'pawfinder-ac326.firebasestorage.app',
    iosBundleId: 'com.example.pawfinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7-H-Dm3EJdcaakEQx_ehWqXJAp2jvgq4',
    appId: '1:809642431817:web:215b6a90ae7ae49de53698',
    messagingSenderId: '809642431817',
    projectId: 'pawfinder-ac326',
    authDomain: 'pawfinder-ac326.firebaseapp.com',
    databaseURL: 'https://pawfinder-ac326-default-rtdb.firebaseio.com',
    storageBucket: 'pawfinder-ac326.firebasestorage.app',
    measurementId: 'G-1S4WJRDVWN',
  );
}
